// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package http

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Author defines model for Author.
type Author struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// Book defines model for Book.
type Book struct {
	Id    openapi_types.UUID `json:"id"`
	Title string             `json:"title"`
}

// BookWithAuthor defines model for BookWithAuthor.
type BookWithAuthor struct {
	Author *Author            `json:"author,omitempty"`
	Id     openapi_types.UUID `json:"id"`
	Title  string             `json:"title"`
}

// CreateBookRequest defines model for CreateBookRequest.
type CreateBookRequest struct {
	Author string `json:"author"`
	Title  string `json:"title"`
}

// GetBookResponse defines model for GetBookResponse.
type GetBookResponse struct {
	Data    Book   `json:"data"`
	Message string `json:"message"`
}

// GetBooksResponse defines model for GetBooksResponse.
type GetBooksResponse struct {
	Data    []BookWithAuthor `json:"data"`
	Message string           `json:"message"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// CreateBookJSONRequestBody defines body for CreateBook for application/json ContentType.
type CreateBookJSONRequestBody = CreateBookRequest
