version: '3.8'
name: 'go-boilerplate'
services:
  http:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      SERVER_TYPE: http
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 5s
      timeout: 2s
      retries: 5
  grpc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8181:8181'
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      SERVER_TYPE: grpc

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boilerplate
    env_file: .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 2s
      retries: 5
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 10
