version: '3.8'
name: 'go-boilerplate'
services:
  http:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file: .env.docker
    environment:
      SERVER_TYPE: http
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 5s
      timeout: 2s
      retries: 5
  grpc:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - '8181:8181'
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file: .env.docker
    environment:
      SERVER_TYPE: grpc
  books-authors-subscriber:
    build:
      context: .
      dockerfile: docker/subscriber/Dockerfile
      args:
        - WORK_DIR=/src/books/cmd/subscriber/authors
    restart: unless-stopped
    depends_on:
      - rabbitmq
    env_file: .env.docker

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boilerplate
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 2s
      retries: 5
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 10
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 5s
      timeout: 2s
      retries: 5
