// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package http

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ProfileResponse defines model for ProfileResponse.
type ProfileResponse struct {
	Data    User   `json:"data"`
	Message string `json:"message"`
}

// User defines model for User.
type User struct {
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	Id        openapi_types.UUID `json:"id"`
	LastName  string             `json:"last_name"`
}
