openapi: "3.0.0"
info:
  version: 0.1.0
  title: Library Authors API
  description: Library Authors API Definition
  contact:
    name: Kevin Yobeth
    url: https://github.com/kevinyobeth
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
paths:
  /authors:
    get:
      tags: [Authors]
      operationId: getAuthors
      description: get all authors
      responses:
        "200":
          description: get all authors success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetAuthorsResponse"
    post:
      tags: [Authors]
      operationId: createAuthor
      description: create author
      requestBody:
        description: create author
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAuthorRequest"   
      responses:
        "200":
          description: create author success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
  /authors/{id}:
    get:
      tags: [Authors]
      operationId: getAuthor
      description: get author
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: author id
      responses:
        "200":
          description: get author success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetAuthorResponse"
    delete:
      tags: [Authors]
      operationId: deleteAuthor
      description: delete author
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: author id
      responses:
        "200":
          description: delete author success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"

components:
  schemas:
    GetAuthorsResponse:
      type: object
      required: [data, message]
      properties:
        message:
          type: string
        data:
          type: array
          items:
            $ref: "#/components/schemas/Author"
    GetAuthorResponse:
      type: object
      required: [data, message]
      properties:
        message:
          type: string
        data:
          type: object
          $ref: "#/components/schemas/Author"
    CreateAuthorRequest:
      type: object
      required: [name]
      properties:
        name:
          type: string

    Author:
      type: object
      required: [id, name]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    MessageResponse:
      type: object
      required: [message]
      properties:
        message:
          type: string