openapi: "3.0.0"
info:
  version: 0.1.0
  title: Authentication API
  description: Authentication API Definition
  contact:
    name: Kevin Yobeth
    url: https://github.com/kevinyobeth
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost

paths:
  /login:
    post:
      tags: [Authentication]
      operationId: login
      description: login user
      requestBody:
        description: login user
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: login user success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
  /register:
    post:
      tags: [Authentication]
      operationId: register
      description: register user
      requestBody:
        description: register user
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "200":
          description: register user success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
  /refresh-token:
    post:
      tags: [Authentication]
      operationId: refreshToken
      description: refresh token
      requestBody:
        description: refresh token
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshTokenRequest"
      responses:
        "200":
          description: refresh token success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
  /user:
    get:
      tags: [Authentication]
      operationId: getUser
      description: get user profile
      responses:
        "200":
          description: get user profile success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"

components:
  schemas:
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
        password:
          type: string
    RegisterRequest:
      type: object
      required: [first_name, last_name, email, password]
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type: string
    RefreshTokenRequest:
      type: object
      required: [refresh_token]
      properties:
        refresh_token:
          type: string

    LoginResponse:
      type: object
      required: [data, message]
      properties:
        message:
          type: string
        data:
          type: string
          $ref: "#/components/schemas/Token"
    UserResponse:
      type: object
      required: [data, message]
      properties:
        message:
          type: string
        data:
          type: object
          $ref: "#/components/schemas/User"
    MessageResponse:
      type: object
      required: [message]
      properties:
        message:
          type: string
    
    Token:
      type: object
      required: [token, expired_at, refresh_token]
      properties:
        token:
          type: string
        expired_at:
          type: string
          format: date-time
        refresh_token:
          type: object
          $ref: "#/components/schemas/RefreshToken"
    RefreshToken:
      type: object
      required: [token, expired_at]
      properties:
        token:
          type: string
        expired_at:
          type: string
          format: date-time
          
    User:
      type: object
      required: [id, first_name, last_name, email]
      properties:
        id:
          type: string
          format: uuid
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string