openapi: "3.0.0"
info:
  version: 0.1.0
  title: Authentication API
  description: Authentication API Definition
  contact:
    name: Kevin Yobeth
    url: https://github.com/kevinyobeth
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost

paths:
  /login:
    post:
      tags: [Authentication]
      operationId: login
      description: login user
      requestBody:
        description: login user
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: login user success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
  /register:
    post:
      tags: [Authentication]
      operationId: register
      description: register user
      requestBody:
        description: register user
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "200":
          description: register user success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"

components:
  schemas:
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
        password:
          type: string
    RegisterRequest:
      type: object
      required: [first_name, last_name, email, password]
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type: string

    MessageResponse:
      type: object
      required: [message]
      properties:
        message:
          type: string