// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package http

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateLinkRequest defines model for CreateLinkRequest.
type CreateLinkRequest struct {
	Description string `json:"description"`
	Slug        string `json:"slug"`
	Url         string `json:"url"`
}

// GetLinkResponse defines model for GetLinkResponse.
type GetLinkResponse struct {
	Data    Link   `json:"data"`
	Message string `json:"message"`
}

// GetLinksResponse defines model for GetLinksResponse.
type GetLinksResponse struct {
	Data     []Link             `json:"data"`
	Message  string             `json:"message"`
	Metadata PaginationMetadata `json:"metadata"`
}

// Link defines model for Link.
type Link struct {
	CreatedAt   time.Time          `json:"created_at"`
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	Slug        string             `json:"slug"`
	Total       int                `json:"total"`
	UpdatedAt   *time.Time         `json:"updated_at,omitempty"`
	Url         string             `json:"url"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// PaginationMetadata defines model for PaginationMetadata.
type PaginationMetadata struct {
	Next *openapi_types.UUID `json:"next,omitempty"`
	Prev *openapi_types.UUID `json:"prev,omitempty"`
}

// UpdateLinkRequest defines model for UpdateLinkRequest.
type UpdateLinkRequest struct {
	Description string `json:"description"`
	Slug        string `json:"slug"`
	Url         string `json:"url"`
}

// GetLinksParams defines parameters for GetLinks.
type GetLinksParams struct {
	// Next next cursor for pagination
	Next *openapi_types.UUID `form:"next,omitempty" json:"next,omitempty"`

	// Prev previous cursor for pagination
	Prev *openapi_types.UUID `form:"prev,omitempty" json:"prev,omitempty"`

	// Limit limit for pagination
	Limit *uint64 `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateLinkJSONRequestBody defines body for CreateLink for application/json ContentType.
type CreateLinkJSONRequestBody = CreateLinkRequest

// UpdateLinkJSONRequestBody defines body for UpdateLink for application/json ContentType.
type UpdateLinkJSONRequestBody = UpdateLinkRequest
