// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: authors.proto

package authors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAuthorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorsRequest) Reset() {
	*x = GetAuthorsRequest{}
	mi := &file_authors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorsRequest) ProtoMessage() {}

func (x *GetAuthorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorsRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorsRequest) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{0}
}

func (x *GetAuthorsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAuthorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Author              `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorsResponse) Reset() {
	*x = GetAuthorsResponse{}
	mi := &file_authors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorsResponse) ProtoMessage() {}

func (x *GetAuthorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorsResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorsResponse) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuthorsResponse) GetData() []*Author {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetAuthorsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_authors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_authors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_authors_proto_rawDescGZIP(), []int{2}
}

func (x *Author) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_authors_proto protoreflect.FileDescriptor

const file_authors_proto_rawDesc = "" +
	"\n" +
	"\rauthors.proto\"'\n" +
	"\x11GetAuthorsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"K\n" +
	"\x12GetAuthorsResponse\x12\x1b\n" +
	"\x04data\x18\x01 \x03(\v2\a.AuthorR\x04data\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2F\n" +
	"\rAuthorService\x125\n" +
	"\n" +
	"GetAuthors\x12\x12.GetAuthorsRequest\x1a\x13.GetAuthorsResponseB!Z\x1fgo-boilerplate/internal/authorsb\x06proto3"

var (
	file_authors_proto_rawDescOnce sync.Once
	file_authors_proto_rawDescData []byte
)

func file_authors_proto_rawDescGZIP() []byte {
	file_authors_proto_rawDescOnce.Do(func() {
		file_authors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authors_proto_rawDesc), len(file_authors_proto_rawDesc)))
	})
	return file_authors_proto_rawDescData
}

var file_authors_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_authors_proto_goTypes = []any{
	(*GetAuthorsRequest)(nil),  // 0: GetAuthorsRequest
	(*GetAuthorsResponse)(nil), // 1: GetAuthorsResponse
	(*Author)(nil),             // 2: Author
}
var file_authors_proto_depIdxs = []int32{
	2, // 0: GetAuthorsResponse.data:type_name -> Author
	0, // 1: AuthorService.GetAuthors:input_type -> GetAuthorsRequest
	1, // 2: AuthorService.GetAuthors:output_type -> GetAuthorsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_authors_proto_init() }
func file_authors_proto_init() {
	if File_authors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authors_proto_rawDesc), len(file_authors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authors_proto_goTypes,
		DependencyIndexes: file_authors_proto_depIdxs,
		MessageInfos:      file_authors_proto_msgTypes,
	}.Build()
	File_authors_proto = out.File
	file_authors_proto_goTypes = nil
	file_authors_proto_depIdxs = nil
}
