// Package transport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package transport

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Author defines model for Author.
type Author struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// CreateAuthorRequest defines model for CreateAuthorRequest.
type CreateAuthorRequest struct {
	Name string `json:"name"`
}

// GetAuthorResponse defines model for GetAuthorResponse.
type GetAuthorResponse struct {
	Data    Author `json:"data"`
	Message string `json:"message"`
}

// GetAuthorsResponse defines model for GetAuthorsResponse.
type GetAuthorsResponse struct {
	Data    []Author `json:"data"`
	Message string   `json:"message"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// CreateAuthorJSONRequestBody defines body for CreateAuthor for application/json ContentType.
type CreateAuthorJSONRequestBody = CreateAuthorRequest
