// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package http

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Booking defines model for Booking.
type Booking struct {
	BookId   openapi_types.UUID `json:"book_id"`
	DateFrom time.Time          `json:"date_from"`
	DateTo   time.Time          `json:"date_to"`
	Id       openapi_types.UUID `json:"id"`
}

// CreateBookingRequest defines model for CreateBookingRequest.
type CreateBookingRequest struct {
	BookId   openapi_types.UUID `json:"book_id"`
	DateFrom time.Time          `json:"date_from"`
	DateTo   time.Time          `json:"date_to"`
}

// GetBookingResponse defines model for GetBookingResponse.
type GetBookingResponse struct {
	Data    Booking `json:"data"`
	Message string  `json:"message"`
}

// GetBookingsResponse defines model for GetBookingsResponse.
type GetBookingsResponse struct {
	Data    []Booking `json:"data"`
	Message string    `json:"message"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// CreateBookingJSONRequestBody defines body for CreateBooking for application/json ContentType.
type CreateBookingJSONRequestBody = CreateBookingRequest
